### ISSUE TITLE
xrt not compiling after merge

### ISSUE THREAD

**Issue by mcstoian** [arhacc/sw#5]
Please try to make sure that everything we push is at least compiling.

[ 33%] Building CXX object CMakeFiles/xrt.dir/src/manager/Manager.cpp.o
[ 33%] Building CXX object CMakeFiles/xrt.dir/src/targets/Targets.cpp.o
[ 50%] Building CXX object CMakeFiles/xrt.dir/src/main.cpp.o
[ 66%] Building CXX object CMakeFiles/xrt.dir/src/sources/Sources.cpp.o
[ 83%] Building CXX object CMakeFiles/xrt.dir/src/transformers/Transformers.cpp.o
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/targets/Targets.cpp:8:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/include/targets/Targets.h:10:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/include/targets/sim/SimTarget.h:9:
/Users/marius/projects/arhacc/sw/tools/xrt/include/targets/sim/xsi_loader.h:208:9: error: unknown type name 't_fp_xsi_generate_clock'
        t_fp_xsi_generate_clock _xsi_generate_clock;
        ^
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/transformers/Transformers.cpp:8:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/include/manager/Manager.h:9:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/include/targets/Targets.h:10:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/include/targets/sim/SimTarget.h:9:
/Users/marius/projects/arhacc/sw/tools/xrt/include/targets/sim/xsi_loader.h:208:9: error: unknown type name 't_fp_xsi_generate_clock'
        t_fp_xsi_generate_clock _xsi_generate_clock;
        ^
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/manager/Manager.cpp:8:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/include/targets/Targets.h:10:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/include/targets/sim/SimTarget.h:9:
/Users/marius/projects/arhacc/sw/tools/xrt/include/targets/sim/xsi_loader.h:208:9: error: unknown type name 't_fp_xsi_generate_clock'
        t_fp_xsi_generate_clock _xsi_generate_clock;
        ^
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/sources/Sources.cpp:8:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/include/transformers/Transformers.h:9:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/include/manager/Manager.h:9:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/include/targets/Targets.h:10:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/include/targets/sim/SimTarget.h:9:
/Users/marius/projects/arhacc/sw/tools/xrt/include/targets/sim/xsi_loader.h:208:9: error: unknown type name 't_fp_xsi_generate_clock'
        t_fp_xsi_generate_clock _xsi_generate_clock;
        ^
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/main.cpp:18:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/include/targets/Targets.h:10:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/include/targets/sim/SimTarget.h:9:
/Users/marius/projects/arhacc/sw/tools/xrt/include/targets/sim/xsi_loader.h:208:9: error: unknown type name 't_fp_xsi_generate_clock'
        t_fp_xsi_generate_clock _xsi_generate_clock;
        ^
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/targets/Targets.cpp:10:
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/fpga/FpgaTarget.cpp:140:19: warning: comparison of integers of different signs: 'int' and 'uint32_t' (aka 'unsigned int') [-Wsign-compare]
        for(int i = 0; i < _length; i++){
                       ~ ^ ~~~~~~~
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/targets/Targets.cpp:11:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/SimTarget.cpp:9:
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/XpuTestBench.cpp:8:38: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
#include "targets/sim/XpuTestBench.h"XpuTestBench::XpuTestBench(const std::string& design_libname, const std::string& simkernel_libname,
                                     ^

/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/XpuTestBench.cpp:8:38: warning: extra tokens at end of #include directive [-Wextra-tokens]
#include "targets/sim/XpuTestBench.h"XpuTestBench::XpuTestBench(const std::string& design_libname, const std::string& simkernel_libname,
                                     ^
                                     //
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/targets/Targets.cpp:10:
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/fpga/FpgaTarget.cpp:952:27: warning: comparison of integers of different signs: 'int' and 'uint32_t' (aka 'unsigned int') [-Wsign-compare]
                for(int j = 0; j < word_size ; j++)
                               ~ ^ ~~~~~~~~~
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/targets/Targets.cpp:11:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/SimTarget.cpp:9:
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/XpuTestBench.cpp:9:24: error: expected unqualified-id
float clock_period_ns, const std::string& clock_name,
                       ^
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/XpuTestBench.cpp:9:23: error: expected ';' after top level declarator
float clock_period_ns, const std::string& clock_name,
                      ^
                      ;
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/XpuTestBench.cpp:9:43: error: declaration of reference variable 'clock_name' requires an initializer
float clock_period_ns, const std::string& clock_name,
                                          ^~~~~~~~~~
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/XpuTestBench.cpp:9:53: error: expected ';' at end of declaration
float clock_period_ns, const std::string& clock_name,
                                                    ^
                                                    ;
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/XpuTestBench.cpp:10:20: error: declaration of reference variable 'reset_name' requires an initializer
const std::string& reset_name):
                   ^~~~~~~~~~
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/XpuTestBench.cpp:10:30: error: expected ';' after top level declarator
const std::string& reset_name):
                             ^
                             ;
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/XpuTestBench.cpp:420:8: error: use of undeclared identifier 'axi_write_count'
    if(axi_write_count == 1)
       ^
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/XpuTestBench.cpp:429:7: error: use of undeclared identifier 'axi_write_count'
    ++axi_write_count;
      ^
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/targets/Targets.cpp:11:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/SimTarget.cpp:10:
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/Xsi_loader.cpp:253:28: error: use of undeclared identifier 't_fp_xsi_generate_clock'
    _xsi_generate_clock = (t_fp_xsi_generate_clock) _simkernel_lib.getfunction("xsi_generate_clock");
                           ^
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/targets/Targets.cpp:8:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/include/targets/Targets.h:10:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/include/targets/sim/SimTarget.h:9:
/Users/marius/projects/arhacc/sw/tools/xrt/include/targets/sim/xsi_loader.h:208:33: warning: private field '_xsi_generate_clock' is not used [-Wunused-private-field]
        t_fp_xsi_generate_clock _xsi_generate_clock;
                                ^
4 warnings and 11 errors generated.
make[2]: *** [CMakeFiles/xrt.dir/src/targets/Targets.cpp.o] Error 1

**Comment by alex13dumi** [comment]
This doesn't compile because you don't have the latest xsi.h and librdi_simulator_kernel.so from a newer version of Vivado. Function pointer t_fp_xsi_generate_clock was introduced in a newer version of XSI. 
I use Vivado 2022.2.

**Comment by mcstoian** [comment]
Can you please put Vitis 2022.2 on athena on /tools/Xilinx/

**Comment by mcstoian** [comment]
with Vivado/2022.2:

[ 16%] Building CXX object CMakeFiles/xrt.dir/src/targets/Targets.cpp.o
[ 33%] Building CXX object CMakeFiles/xrt.dir/src/manager/Manager.cpp.o
[ 50%] Building CXX object CMakeFiles/xrt.dir/src/transformers/Transformers.cpp.o
[ 66%] Building CXX object CMakeFiles/xrt.dir/src/sources/Sources.cpp.o
[ 83%] Building CXX object CMakeFiles/xrt.dir/src/main.cpp.o
In file included from In file included from In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/transformers/Transformers.cpp/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/Targets.cpp:8/Users/marius/projects/arhacc/sw/tools/xrt/src/sources/Sources.cpp:
:In file included from 8/Users/marius/projects/arhacc/sw/tools/xrt/include/targets/Targets.h:
:In file included from /Users/marius/projects/arhacc/sw/tools/xrt/include/transformers/Transformers.h:109:
:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/include/targets/sim/SimTarget.h:9:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/main.cpp:/Users/marius/projects/arhacc/sw/tools/xrt/include/targets/sim/xsi_loader.h:20818:In file included from :
/Users/marius/projects/arhacc/sw/tools/xrt/include/manager/Manager.hIn file included from :/Users/marius/projects/arhacc/sw/tools/xrt/include/targets/Targets.h9::
10:In file included from :
89:
In file included from :/Users/marius/projects/arhacc/sw/tools/xrt/include/targets/Targets.h In file included from /Users/marius/projects/arhacc/sw/tools/xrt/include/manager/Manager.h:10::
9In file included from /Users/marius/projects/arhacc/sw/tools/xrt/include/targets/sim/SimTarget.h/Users/marius/projects/arhacc/sw/tools/xrt/include/targets/sim/SimTarget.h:9:
error: ::
/Users/marius/projects/arhacc/sw/tools/xrt/include/targets/sim/xsi_loader.h9:208:9: error: unknown type name 't_fp_xsi_generate_clock'
:
/Users/marius/projects/arhacc/sw/tools/xrt/include/targets/sim/xsi_loader.h:208:9: error: unknown type name 't_fp_xsi_generate_clock'
unknown type name 't_fp_xsi_generate_clock'
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/include/targets/Targets.h:10:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/include/targets/sim/SimTarget.h:9:
/Users/marius/projects/arhacc/sw/tools/xrt/include/targets/sim/xsi_loader.h:208:9: error:         t_fp_xsi_generate_clock _xsi_generate_clock;unknown type name 't_fp_xsi_generate_clock'        t_fp_xsi_generate_clock _xsi_generate_clock;


        ^
        ^
        t_fp_xsi_generate_clock _xsi_generate_clock;
        ^
        t_fp_xsi_generate_clock _xsi_generate_clock;
        ^
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/manager/Manager.cpp:8:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/include/targets/Targets.h:10:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/include/targets/sim/SimTarget.h:9:
/Users/marius/projects/arhacc/sw/tools/xrt/include/targets/sim/xsi_loader.h:208:9: error: unknown type name 't_fp_xsi_generate_clock'
        t_fp_xsi_generate_clock _xsi_generate_clock;
        ^
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/targets/Targets.cpp:10:
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/fpga/FpgaTarget.cpp:140:19: warning: comparison of integers of different signs: 'int' and 'uint32_t' (aka 'unsigned int') [-Wsign-compare]
        for(int i = 0; i < _length; i++){
                       ~ ^ ~~~~~~~
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/fpga/FpgaTarget.cpp:952:27: warning: comparison of integers of different signs: 'int' and 'uint32_t' (aka 'unsigned int') [-Wsign-compare]
                for(int j = 0; j < word_size ; j++)
                               ~ ^ ~~~~~~~~~
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/targets/Targets.cpp:11:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/SimTarget.cpp:9:
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/XpuTestBench.cpp:111:19: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
    for(int i=0; i<n; i++)
                 ~^~
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/XpuTestBench.cpp:129:23: warning: compound literals are a C99-specific feature [-Wc99-extensions]
    logic_val.at(0) = (s_xsi_vlog_logicval){val, 0};
                      ^
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/XpuTestBench.cpp:132:27: warning: compound literals are a C99-specific feature [-Wc99-extensions]
        logic_val.at(i) = (s_xsi_vlog_logicval) {0, 0};
                          ^
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/XpuTestBench.cpp:130:19: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
    for(int i=1; i<nwords; i++)
                 ~^~~~~~~
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/XpuTestBench.cpp:209:19: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
    for(int i=0; i<nr_clock_cycles-1; i++)
                 ~^~~~~~~~~~~~~~~~~~
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/targets/Targets.cpp:11:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/SimTarget.cpp:10:
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/Xsi_loader.cpp:253:28: error: use of undeclared identifier 't_fp_xsi_generate_clock'
    _xsi_generate_clock = (t_fp_xsi_generate_clock) _simkernel_lib.getfunction("xsi_generate_clock");
                           ^
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/targets/Targets.cpp:8:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/include/targets/Targets.h:10:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/include/targets/sim/SimTarget.h:9:
/Users/marius/projects/arhacc/sw/tools/xrt/include/targets/sim/xsi_loader.h:208:33: warning: private field '_xsi_generate_clock' is not used [-Wunused-private-field]
        t_fp_xsi_generate_clock _xsi_generate_clock;
                                ^
8 warnings and 2 errors generated.
make[2]: *** [CMakeFiles/xrt.dir/src/targets/Targets.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/manager/Manager.cpp:11:
/Users/marius/projects/arhacc/sw/tools/xrt/src/manager/libmanager/LibManager.cpp:71:33: warning: comparison of integers of different signs: 'uint32_t' (aka 'unsigned int') and 'int' [-Wsign-compare]
    if(_functionInfo -> address != -1){
       ~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~
1 warning and 1 error generated.
make[2]: *** [CMakeFiles/xrt.dir/src/manager/Manager.cpp.o] Error 1
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/transformers/Transformers.cpp:12:
/Users/marius/projects/arhacc/sw/tools/xrt/src/transformers/onnx/OnnxTransformer.cpp:55:24: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
  for (size_t i = 0; i < graph.value_info_size(); i++) {
                     ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/sources/Sources.cpp:14:
/Users/marius/projects/arhacc/sw/tools/xrt/src/sources/file/FileSource.cpp:12:20: warning: comparison of integers of different signs: 'int' and 'std::vector<std::string>::size_type' (aka 'unsigned long') [-Wsign-compare]
        for (int i = 0; i < _files.size(); i++) {
                        ~ ^ ~~~~~~~~~~~~~
1 warning and 1 error generated.
make[2]: *** [CMakeFiles/xrt.dir/src/transformers/Transformers.cpp.o] Error 1
1 error generated.
make[2]: *** [CMakeFiles/xrt.dir/src/main.cpp.o] Error 1
1 warning and 1 error generated.
make[2]: *** [CMakeFiles/xrt.dir/src/sources/Sources.cpp.o] Error 1
make[1]: *** [CMakeFiles/xrt.dir/all] Error 2
make: *** [all] Error 2

**Comment by alex13dumi** [comment]
In tools/xrt/targets/CMakeLists.txt i don't see the **_path_** to Vivado, only Vitis. Try and update that.

**Comment by mcstoian** [comment]
can you be more precise. please provide a list with directories that needs to be put in path.

**Comment by mcstoian** [comment]
I've disconnected SimTarget from XRT until it becomes compilable again so we can continue work on XRT

**Comment by mcstoian** [comment]
I made the changes as per your instructions:

[ 33%] Building CXX object CMakeFiles/xrt.dir/src/targets/Targets.cpp.o
[ 33%] Building CXX object CMakeFiles/xrt.dir/src/manager/Manager.cpp.o
[ 50%] Building CXX object CMakeFiles/xrt.dir/src/transformers/Transformers.cpp.o
[ 66%] Building CXX object CMakeFiles/xrt.dir/src/sources/Sources.cpp.o
[ 83%] Building CXX object CMakeFiles/xrt.dir/src/main.cpp.o
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/targets/Targets.cpp:10:
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/fpga/FpgaTarget.cpp:140:19: warning: comparison of integers of different signs: 'int' and 'uint32_t' (aka 'unsigned int') [-Wsign-compare]
        for(int i = 0; i < _length; i++){
                       ~ ^ ~~~~~~~
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/fpga/FpgaTarget.cpp:952:27: warning: comparison of integers of different signs: 'int' and 'uint32_t' (aka 'unsigned int') [-Wsign-compare]
                for(int j = 0; j < word_size ; j++)
                               ~ ^ ~~~~~~~~~
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/targets/Targets.cpp:11:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/SimTarget.cpp:9:
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/XpuTestBench.cpp:111:19: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
    for(int i=0; i<n; i++)
                 ~^~
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/XpuTestBench.cpp:129:23: warning: compound literals are a C99-specific feature [-Wc99-extensions]
    logic_val.at(0) = (s_xsi_vlog_logicval){val, 0};
                      ^
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/XpuTestBench.cpp:132:27: warning: compound literals are a C99-specific feature [-Wc99-extensions]
        logic_val.at(i) = (s_xsi_vlog_logicval) {0, 0};
                          ^
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/XpuTestBench.cpp:130:19: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
    for(int i=1; i<nwords; i++)
                 ~^~~~~~~
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/XpuTestBench.cpp:209:19: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
    for(int i=0; i<nr_clock_cycles-1; i++)
                 ~^~~~~~~~~~~~~~~~~~
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/targets/Targets.cpp:11:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/SimTarget.cpp:10:
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/Xsi_loader.cpp:49:9: error: member initializer '_xsi_generate_clock' does not name a non-static data member or base class
        _xsi_generate_clock(nullptr)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/Xsi_loader.cpp:153:5: error: use of undeclared identifier '_xsi_generate_clock'; did you mean 'xsi_generate_clock'?
    _xsi_generate_clock(_design_handle, port_number, timeLow, timeHigh);
    ^~~~~~~~~~~~~~~~~~~
    xsi_generate_clock
/Users/marius/apps/Xilinx/Vivado/2022.2/data/xsim/include/xsi.h:334:24: note: 'xsi_generate_clock' declared here
     XSI_DLLESPEC void xsi_generate_clock(xsiHandle design_handle, XSI_INT32 port_number,  XSI_UINT64 timeLow,  XSI_UINT64 timeHigh);
                       ^
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/targets/Targets.cpp:11:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/SimTarget.cpp:10:
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/Xsi_loader.cpp:253:5: error: use of undeclared identifier '_xsi_generate_clock'
    _xsi_generate_clock = (t_fp_xsi_generate_clock) _simkernel_lib.getfunction("xsi_generate_clock");
    ^
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/Xsi_loader.cpp:254:10: error: use of undeclared identifier '_xsi_generate_clock'; did you mean 'xsi_generate_clock'?
    if (!_xsi_generate_clock)
         ^~~~~~~~~~~~~~~~~~~
         xsi_generate_clock
/Users/marius/apps/Xilinx/Vivado/2022.2/data/xsim/include/xsi.h:334:24: note: 'xsi_generate_clock' declared here
     XSI_DLLESPEC void xsi_generate_clock(xsiHandle design_handle, XSI_INT32 port_number,  XSI_UINT64 timeLow,  XSI_UINT64 timeHigh);
                       ^
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/targets/Targets.cpp:11:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/SimTarget.cpp:10:
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/Xsi_loader.cpp:254:10: warning: address of function 'xsi_generate_clock' will always evaluate to 'true' [-Wpointer-bool-conversion]
    if (!_xsi_generate_clock)
        ~^~~~~~~~~~~~~~~~~~~
/Users/marius/projects/arhacc/sw/tools/xrt/src/targets/sim/Xsi_loader.cpp:254:10: note: prefix with the address-of operator to silence this warning
    if (!_xsi_generate_clock)
         ^
         &
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/manager/Manager.cpp:11:
/Users/marius/projects/arhacc/sw/tools/xrt/src/manager/libmanager/LibManager.cpp:71:33: warning: comparison of integers of different signs: 'uint32_t' (aka 'unsigned int') and 'int' [-Wsign-compare]
    if(_functionInfo -> address != -1){
       ~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~
/Users/marius/projects/arhacc/sw/tools/xrt/src/manager/libmanager/LibManager.cpp:75:1: warning: non-void function does not return a value in all control paths [-Wreturn-type]
}
^
/Users/marius/projects/arhacc/sw/tools/xrt/src/manager/libmanager/LibManager.cpp:80:1: warning: non-void function does not return a value [-Wreturn-type]
}
^
/Users/marius/projects/arhacc/sw/tools/xrt/src/manager/libmanager/LibManager.cpp:85:1: warning: non-void function does not return a value [-Wreturn-type]
}
^
8 warnings and 4 errors generated.
make[2]: *** [CMakeFiles/xrt.dir/src/targets/Targets.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/transformers/Transformers.cpp:14:
/Users/marius/projects/arhacc/sw/tools/xrt/src/transformers/onnx/OnnxTransformer.cpp:55:24: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/main.cpp:22:
/Users/marius/projects/arhacc/sw/tools/xrt/src/common/Utils.cpp:63:1:   for (size_t i = 0; i < graph.value_info_size(); i++) {
warning:                      ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~
non-void function does not return a value [-Wreturn-type]
}
^
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/sources/Sources.cpp:12:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/sources/net/NetSource.cpp:9:
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/sources/net/stack/ApplicationLayer.cpp:8:
/Users/marius/projects/arhacc/sw/tools/xrt/src/sources/net/stack/CommandLayer.cpp:134:27: warning: variable length arrays are a C99 feature [-Wvla-extension]
    unsigned char _string[_length];
                          ^~~~~~~
/Users/marius/projects/arhacc/sw/tools/xrt/src/sources/net/stack/CommandLayer.cpp:134:27: note: read of non-const variable '_length' is not allowed in a constant expression
/Users/marius/projects/arhacc/sw/tools/xrt/src/sources/net/stack/CommandLayer.cpp:133:9: note: declared here
    int _length = receiveInt();
        ^
In file included from /Users/marius/projects/arhacc/sw/tools/xrt/src/sources/Sources.cpp:14:
/Users/marius/projects/arhacc/sw/tools/xrt/src/sources/file/FileSource.cpp:12:20: warning: comparison of integers of different signs: 'int' and 'std::vector<std::string>::size_type' (aka 'unsigned long') [-Wsign-compare]
        for (int i = 0; i < _files.size(); i++) {
                        ~ ^ ~~~~~~~~~~~~~
4 warnings generated.
1 warning generated.
1 warning generated.
2 warnings generated.
make[1]: *** [CMakeFiles/xrt.dir/all] Error 2
make: *** [all] Error 2

**Comment by alex13dumi** [comment]
![image](https://user-images.githubusercontent.com/75372314/223358604-dd6b311c-8ead-4cd4-aca9-b13aaae02846.png)

This screenshot was taken from commit "**_disconnect SimTarget from XRT_**" .
Try to uncomment line 208 from tools/xrt/include/targets/sim/xsi_loader.h and then compile again.
